services:
  - type: web
    name: customer-churn-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app/inference_entrypoint.py
    envVars:
      - key: MODEL_PATH
        value: /opt/render/project/src/models/xgboost_model.pkl
      - key: TEST_DATA_PATH
        value: /opt/render/project/src/data/raw/InferenceData.csv
      - key: INFERENCE_CLEANED_PATH
        value: /opt/render/project/src/data/cleaned/InferenceCleaned.csv