name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8 pytest

      # Step 4: Auto-format with Black and isort
      - name: Auto format with black and isort
        run: |
          black src/ --line-length 120
          isort src/

      # Step 5: Lint with flake8
      - name: Lint with flake8
        run: |
          echo "[flake8]" > .flake8
          echo "max-line-length = 120" >> .flake8
          echo "ignore = E203, W503, W291, W293" >> .flake8
          flake8 src/

      # Step 6: Run unit tests
      - name: Run tests with pytest
        run: |
          pytest tests/
